# example GitHub workflow

name: Publish resume in JSONResume format as Github Page
 
on:
  push:
    branches: [ "master" , "feature/resume" ]

jobs:
  check_run:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - run: echo "${{ github.event.head_commit.message }}"

  build:
    runs-on: ubuntu-latest
    needs: check_run
    steps:
      - uses: actions/checkout@v2
      - uses: kelvintaywl/action-jsonresume-export@v1
        name: Export resume as HTML
        with:
          theme: elegant
          resume_filepath: Alexandre_Touret.resume_EN.json
          # modifies the index.html in-place
          output_filepath: docs/Alexandre_Touret.resume_EN.html
      - name: Commit published HTML
        id: commit
        run: |
          git config --local user.email "${{ secrets.GITHUBUSEREMAIL}}"
          git config --local user.name "${{ secrets.GITHUBUSERNAME}}"
          if [ -n "$(git status --porcelain docs/)" ]; then
            git add docs/
            git commit -m "[ci skip] chore(docs/): update resume page"
            echo ::set-output name=exit_code::0
          else
            echo ::set-output name=exit_code::1
          fi
      - name: Push changes
        uses: ad-m/github-push-action@master
        if: steps.commit.outputs.exit_code == 0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}